AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: reInforce 2024 - APS332 - Order service - Attach table access policy to Lambda IAM role
Parameters:
  OrderTableAccessRole:
    Type: String
    Description: ARN of the table access role
  OrderFunctionRole:
    Type: String
    Description: Name of the Lambda function role

Resources:
# workaround circular dependency
  AssumeResourceAccessRole:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AssumeOrderTableAccessRole
            Effect: Allow
            Action:
              - sts:AssumeRole
              - sts:TagSession
            Resource: !Ref OrderTableAccessRole
      Roles: 
        - !Ref OrderFunctionRole

Outputs:
  AssumeResourceAccessRole:
    Description: Resource access policy to be attached to the Lambda function
    Value: !Ref AssumeResourceAccessRole
