AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM template for OpenAPI Generator Agent Lambda function using Strands framework'

Parameters:
  BedrockModel:
    Type: String
    Description: Amazon Bedrock model to be used by the agent
    Default: us.anthropic.claude-3-5-sonnet-20240620-v1:0

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.13

Resources:
  OpenApiGeneratorAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.lambda_handler
      Description: OpenAPI Generator Agent Lambda function that generates OpenAPI specifications using Bedrock Knowledge Base
      Environment:
        Variables:
          BEDROCK_MODEL: !Ref BedrockModel
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: 
                - "arn:aws:bedrock:*:*:*"
Outputs:
  OpenApiGeneratorAgentFunctionArn:
    Description: ARN of the OpenAPI Generator Agent Lambda function
    Value: !GetAtt OpenApiGeneratorAgentFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-OpenApiGeneratorAgentFunctionArn"
  
  OpenApiGeneratorAgentFunctionName:
    Description: Name of the OpenAPI Generator Agent Lambda function
    Value: !Ref OpenApiGeneratorAgentFunction
    Export:
      Name: !Sub "${AWS::StackName}-OpenApiGeneratorAgentFunctionName"