# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. 
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to retrieve API Gateway configurations

Resources:
  APIConfigurationRetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
          # Allow inspection of the APIs and related resources in the account in read-only mode
            - Effect: Allow
              Action:
                - apigateway:GET
                - apigateway:Get* 
                - wafv2:GetWebACL
                - wafv2:ListWebACLs
                - wafv2:GetWebACLForResource
                - wafv2:ListResourcesForWebACL
                - servicequotas:ListServiceQuotas
              Resource: '*'
  FunctionInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref APIConfigurationRetrieverFunction
      Principal: bedrock.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:aws:bedrock:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':*'

Outputs:
  APIConfigurationRetrieverFunction:
    Description: "API Configuration Retriever Lambda Function ARN"
    Value: !GetAtt APIConfigurationRetrieverFunction.Arn
  APIConfigurationRetrieverFunctionName:
    Description: "API Configuration Retriever Lambda Function Name"
    Value: !Ref APIConfigurationRetrieverFunction