AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reInforce 2024 - APS332 - Sample Coffee Shop
Parameters:
  AdminEmail:
    Type: String
  MktgEmail:
    Type: String
  DatascientistEmail:
    Type: String
  Customer1Email:
    Type: String
  Customer2Email:
    Type: String
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Order service VPC
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Order service subnet 1
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Order service subnet 2
    
Resources:
  OrderServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - PaymentServiceStack
    - FulfillmentServiceStack
    Properties:
      TemplateURL: order/template.yaml
      Parameters:
        AdminEmail: !Ref AdminEmail
        MktgEmail: !Ref MktgEmail
        DatascientistEmail: !Ref DatascientistEmail
        Customer1Email: !Ref Customer1Email
        Customer2Email: !Ref Customer2Email
        VpcId: !Ref VpcId
        Subnet1: !Ref Subnet1
        Subnet2: !Ref Subnet2
        OrderServiceSecurityGroup: !GetAtt PaymentServiceStack.Outputs.VpceSecurityGroup
        VpceDnsName: !Select [1, !Split [":", !GetAtt PaymentServiceStack.Outputs.VpceDns]]
        PaymentsApi: !GetAtt PaymentServiceStack.Outputs.PaymentsApiDns
        ApiStage: !GetAtt PaymentServiceStack.Outputs.PaymentsApiStage
        FulfillmentQArn: !GetAtt FulfillmentServiceStack.Outputs.FulfillmentQArn
        FulfillmentQUrl: !GetAtt FulfillmentServiceStack.Outputs.FulfillmentQUrl

  # Need this to avoid circular dependency between the Lambda role and the role it assumes
  PolicyStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - OrderServiceStack
    Properties:
      TemplateURL: order/policy-template.yaml
      Parameters:
        OrderTableAccessRole: !GetAtt OrderServiceStack.Outputs.OrderTableAccessRole
        OrderFunctionRole: !GetAtt OrderServiceStack.Outputs.OrderFunctionRole

  PaymentServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: payment/template.yaml
      Parameters:
        VpcId: !Ref VpcId
        Subnet1: !Ref Subnet1
        Subnet2: !Ref Subnet2

  FulfillmentServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - PaymentServiceStack
    Properties:
      TemplateURL: fulfillment/template.yaml
      Parameters:
        VpcId: !Ref VpcId
        Subnet1: !Ref Subnet1
        Subnet2: !Ref Subnet2
        VpceSecurityGroup: !GetAtt PaymentServiceStack.Outputs.VpceSecurityGroup
        FulfillmentApiVpcEndpoint: !GetAtt PaymentServiceStack.Outputs.ApiVpcEndpoint

  RewardsServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - OrderServiceStack
    Properties:
      TemplateURL: rewards/template.yaml
      Parameters:
        OrderTableName: !GetAtt OrderServiceStack.Outputs.OrderTableName
        OrderTableArn: !GetAtt OrderServiceStack.Outputs.OrderTableArn
        CognitoUserPoolId: !GetAtt OrderServiceStack.Outputs.CognitoUserPool

Outputs:
  CognitoUserPool:
    Description: Cognito user pool id
    Value: !GetAtt OrderServiceStack.Outputs.CognitoUserPool
  CognitoUserPoolClient:
    Description: Cognito user pool client id
    Value: !GetAtt OrderServiceStack.Outputs.CognitoUserPoolClient
  OrderServiceApi:
    Description: Order service API
    Value: !GetAtt OrderServiceStack.Outputs.OrderApi
  OrdersTable:
    Description: Order table
    Value: !GetAtt OrderServiceStack.Outputs.OrderTableName
  PaymentServiceApi:
    Description: Payment service API
    Value: !GetAtt PaymentServiceStack.Outputs.PaymentsApi
  FulfillmentServiceQueue:
    Description: Fulfillment service queue
    Value: !GetAtt FulfillmentServiceStack.Outputs.FulfillmentQUrl
  FilfillmentServiceApi:
    Description: Fulfillment service API
    Value: !GetAtt FulfillmentServiceStack.Outputs.FulfillmentApi
  FulfillmentTable:
    Description: Fulfillment table
    Value: !GetAtt FulfillmentServiceStack.Outputs.FulfillmentTableName
  ApiVpceDns:
    Description: API Gateway VPC endpoint DNS
    Value: !Select [1, !Split [":", !GetAtt PaymentServiceStack.Outputs.VpceDns]]
  RewardsApi:
    Description: Rewards service API
    Value: !GetAtt RewardsServiceStack.Outputs.RewardsApi